# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory
WORKDIR /deployment/api

# Copy the current directory contents into the container at /deployment/api
COPY . .

# Install the necessary packages
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
RUN pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir fastapi pillow python-multipart uvicorn

# Expose the port that FastAPI will run on
EXPOSE 8001 

# Command to run the API using uvicorn
CMD ["uvicorn", "deployment.api.app:app", "--host", "0.0.0.0", "--port", "8001 ", "--reload"]

